// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgBuaWpx5ifdGybE4D-o77Km89ZibWq_c',
    appId: '1:279444368689:web:ce21c7ea52a8a230269410',
    messagingSenderId: '279444368689',
    projectId: 'muscle-growth-tracker-171aa',
    authDomain: 'muscle-growth-tracker-171aa.firebaseapp.com',
    storageBucket: 'muscle-growth-tracker-171aa.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJm_xweH2OBRwl9HkHtvSVlWl9o5I0CYA',
    appId: '1:279444368689:ios:ee025b8a2050912b269410',
    messagingSenderId: '279444368689',
    projectId: 'muscle-growth-tracker-171aa',
    storageBucket: 'muscle-growth-tracker-171aa.firebasestorage.app',
    iosBundleId: 'com.example.src',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJm_xweH2OBRwl9HkHtvSVlWl9o5I0CYA',
    appId: '1:279444368689:ios:ee025b8a2050912b269410',
    messagingSenderId: '279444368689',
    projectId: 'muscle-growth-tracker-171aa',
    storageBucket: 'muscle-growth-tracker-171aa.firebasestorage.app',
    iosBundleId: 'com.example.src',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD26WrE-5ilFZBmgJvBHN1wtxpx69sR6Y',
    appId: '1:279444368689:android:2cb0992a81751de5269410',
    messagingSenderId: '279444368689',
    projectId: 'muscle-growth-tracker-171aa',
    storageBucket: 'muscle-growth-tracker-171aa.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgBuaWpx5ifdGybE4D-o77Km89ZibWq_c',
    appId: '1:279444368689:web:c1dbd35fee0fe1ed269410',
    messagingSenderId: '279444368689',
    projectId: 'muscle-growth-tracker-171aa',
    authDomain: 'muscle-growth-tracker-171aa.firebaseapp.com',
    storageBucket: 'muscle-growth-tracker-171aa.firebasestorage.app',
  );
}
